---
- name: Deploy CoreDNS to Portainer
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml
    - secrets.yml
  tasks:
    - name: Set deployment variables
      set_fact:
        stack_name: "coredns"
        docker_compose_path: "./coredns/docker-compose.yml"
        validate_certs: false
        local_ip: "{{ ansible_default_ipv4.address }}"
  
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ portainer_ip }}"
        port: 22
        delay: 2
        timeout: 300
        state: started
      delegate_to: localhost

    - name: Add VM to inventory
      add_host:
        name: "{{ portainer_ip }}"
        groups: new_vms
        ansible_user: "{{ coreos_username }}"
        ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    - name: Check if CoreDNS image exists
      ansible.builtin.raw: podman images | grep -q "coredns/coredns[ ]*1.12.0"
      become: true
      delegate_to: "{{ portainer_ip }}"
      register: coredns_image_exists
      failed_when: false
      changed_when: false

    - name: Download and load coreDNS image from local server
      ansible.builtin.raw: |
        cd /tmp && 
        curl -o coredns.tar http://{{ local_ip }}:{{ http_file_server_port }}/coredns.tar && 
        podman load -i coredns.tar &&
        rm -f coredns.tar
      become: true
      delegate_to: "{{ portainer_ip }}"
      when: coredns_image_exists.rc != 0

    - name: Create new resolved.conf with DNSStubListener disabled
      ansible.builtin.raw: |
        echo '[Resolve]' > /etc/systemd/resolved.conf
        echo 'DNSStubListener=no' >> /etc/systemd/resolved.conf
      become: true
      delegate_to: "{{ portainer_ip }}"

    - name: Restart systemd-resolved service
      ansible.builtin.raw: systemctl restart systemd-resolved
      become: true
      delegate_to: "{{ portainer_ip }}"

- import_playbook: portainer_deploy.yml
