---
- name: Deploy CoreDNS to Portainer
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml
    - secrets.yml
  tasks:
    - name: Set deployment variables
      set_fact:
        stack_name: "coredns"
        docker_compose_path: "./coredns/docker-compose.yml"
        validate_certs: false
        local_ip: "{{ ansible_default_ipv4.address }}"
  
    - name: Download and load coreDNS image from local server
      ansible.builtin.raw: |
        cd /tmp && 
        curl -o coredns.tar http://{{ local_ip }}:{{ http_file_server_port }}/coredns.tar && 
        podman load -i coredns.tar &&
        rm -f coredns.tar
      become: true
      delegate_to: "{{ portainer_ip }}"

- import_playbook: portainer_deploy.yml
