version: '3'

services:
  coredns:
    image: coredns/coredns:1.12.0
    container_name: coredns
    restart: unless-stopped
    ports:
      - "10.20.177.111:53:53/udp"
      - "10.20.177.111:53:53/tcp"
    volumes:
      - corefile_data:/Corefile
      - /var/run/podman/podman.sock:/var/run/docker.sock:ro
    command: -conf /Corefile
    
volumes:
  corefile_data:
