---
# Molecule test - syntax validation only

platforms: []

scenario:
  test_sequence:
    - syntax
provisioner:
  inventory:
    group_vars:
      all:
        nexus_enabled: true
        nexus_data_dir: "/tmp/nexus"
