---
# Find the IP address that Proxmox can reach
- name: Get local IP address
  set_fact:
    local_ip: "{{ ansible_default_ipv4.address }}"    
    # if running WSL2
    # netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8000 connectaddress=172.22.33.97
    # netsh advfirewall firewall add rule name="Allow TCP Port 8000" dir=in action=allow protocol=TCP localport=8000
    # TURN OFF WHEN DONE:
    # netsh interface portproxy delete v4tov4 listenport=8000 listenaddress=0.0.0.0
    # netsh interface portproxy show all
    # local_ip: "10.0.3.123"

# Prepare local download cache directory
- name: Host CoreOS qcow2 image {{ coreos_qcow2_img_filename }} via HTTP file server
  include_role:
    name: http_file_server
  vars:
    file_to_serve: "{{ coreos_qcow2_img_filename }}"
    server_port: "{{ http_file_server_port }}"
    local_filename: "{{ coreos_qcow2_img_filename }}"
    file_download_url: "{{ coreos_qcow2_url }}"
    file_download_filename: "{{ coreos_qcow2_xz_filename }}"
    extracted_filename: "{{ coreos_qcow2_final_filename }}"
    renamed_filename: "{{ coreos_qcow2_img_filename }}"
    # http_file_server_port: "{{ http_file_server_port }}"
  # when: not core_qcow_exists or wrong_size_file

- name: Ensure SSH key exists
  ansible.builtin.command:
    cmd: "ssh-keygen -t rsa -b 4096 -f {{ ssh_private_key_path }} -N ''"
  args:
    creates: "{{ ssh_public_key_path }}"

- name: Read SSH public key
  ansible.builtin.slurp:
    src: "{{ ssh_public_key_path }}"
  register: ssh_key

- name: Check for Proxmox API password in environment
  set_fact:
    proxmox_api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
  when: lookup('env', 'PROXMOX_API_PASSWORD') != ""

- name: Prompt for Proxmox API password if not set
  pause:
    prompt: "Please enter the Proxmox password"
    echo: no
  register: proxmox_api_password_prompt
  when: proxmox_api_password is not defined or proxmox_api_password == ""

- name: Set Proxmox API password from prompt
  set_fact:
    proxmox_api_password: "{{ proxmox_api_password_prompt.user_input }}"
  when: proxmox_api_password_prompt is defined and proxmox_api_password_prompt.user_input is defined

- name: Obtain Proxmox API ticket
  uri:
    url: "https://{{ proxmox_api_host }}:8006/api2/json/access/ticket"
    method: POST
    body:
      username: "{{ proxmox_api_user }}"
      password: "{{ proxmox_api_password }}"
    body_format: form-urlencoded
    validate_certs: false
  register: pve_ticket
  
- name: Set authentication cookies and CSRF token
  set_fact:
    pve_auth_cookie: "{{ pve_ticket.json.data.ticket }}"
    pve_csrf_token: "{{ pve_ticket.json.data.CSRFPreventionToken }}"

# - name: Check if qcow2.img exists on proxmox
#   uri:
#     url: "https://{{ proxmox_api_host }}:8006/api2/json/nodes/{{ proxmox_node_name }}/storage/{{ storage_pool }}/content"
#     method: GET
#     headers:
#       Cookie: "PVEAuthCookie={{ pve_auth_cookie }}"
#       CSRFPreventionToken: "{{ pve_csrf_token }}"
#     validate_certs: false
#   register: storage_content
#   failed_when: false

- name: Check if CoreOS QCOW2 exists and is correct size on remote proxmox /tmp/ directory using ssh command
  ansible.builtin.stat:
    path: "/tmp/{{ coreos_qcow2_img_filename }}"
  register: core_qcow_exists
  delegate_to: "{{ proxmox_api_host }}"
  vars:
    ansible_user: "{{ proxmox_api_username }}"
    ansible_password: "{{ proxmox_api_password }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  changed_when: false

# - name: Check if CoreOS QCOW2 exists
#   set_fact:
#     core_qcow_exists: "{{ storage_content.json.data | selectattr('volid', 'equalto', storage_pool + ':iso/' + coreos_qcow2_img_filename) | list | length > 0 }}"

# - name: Check if CoreOS QCOW2 exists with correct size
#   set_fact:
#     file_correct_size: "{{ storage_content.json.data | selectattr('volid', 'equalto', storage_pool + ':iso/' + coreos_qcow2_img_filename) | selectattr('size', 'equalto', 1811611648) | list | length > 0 }}"
#     when: core_qcow_exists

# - name: Check if file exists with incorrect size
#   set_fact:
#     wrong_size_file: "{{ core_qcow_exists and not file_correct_size }}"

# - name: Delete existing file with incorrect size
#   uri:
#     url: "https://{{ proxmox_api_host }}:8006/api2/extjs/nodes/{{ proxmox_node_name }}/storage/{{ storage_pool }}/content//{{ storage_pool }}:iso/{{ coreos_qcow2_img_filename }}?delay=5"
#     method: DELETE
#     headers:
#       Cookie: "PVEAuthCookie={{ pve_auth_cookie }}"
#       CSRFPreventionToken: "{{ pve_csrf_token }}"
#     validate_certs: false
#   # register: delete_file_result
#   when: wrong_size_file
  
# - name: Wait for file deletion to complete
#   uri:
#     url: "https://{{ proxmox_api_host }}:8006/api2/json/nodes/{{ proxmox_node_name }}/storage/{{ storage_pool }}/content"
#     method: GET
#     headers:
#       Cookie: "PVEAuthCookie={{ pve_auth_cookie }}"
#       CSRFPreventionToken: "{{ pve_csrf_token }}"
#     validate_certs: false
#   register: deletion_check
#   until: deletion_check.json.data | selectattr('volid', 'equalto', storage_pool + ':iso/' + coreos_qcow2_img_filename) | list | length == 0
#   retries: 10
#   delay: 3
#   when: wrong_size_file

- name: Use SCP to copy CoreOS QCOW2 image to Proxmox /tmp/ directory (this is a workaround for Proxmox not supporting direct HTTP downloads of QCOW2 files). ssh creds are proxmox_api_user and proxmox_api_password
  ansible.builtin.copy:
    src: "{{ coreos_qcow2_img_filename }}"
    dest: "/tmp/{{ coreos_qcow2_img_filename }}"
  delegate_to: "{{ proxmox_api_host }}"
  vars:
    ansible_user: "{{ proxmox_api_username }}"
    ansible_password: "{{ proxmox_api_password }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  when: not core_qcow_exists.stat.exists
    
# - name: Download QCOW2 to Proxmox {{ proxmox_node_name }}/storage/{{ storage_pool }} from http://{{ local_ip }}:{{ http_file_server_port }}/{{ coreos_qcow2_img_filename }}
#   uri:
#     url: "https://{{ proxmox_api_host }}:8006/api2/json/nodes/{{ proxmox_node_name }}/storage/{{ storage_pool }}/download-url"
#     method: POST
#     headers:
#       Cookie: "PVEAuthCookie={{ pve_auth_cookie }}"
#       CSRFPreventionToken: "{{ pve_csrf_token }}"
#     body:
#       content: "iso"  # Proxmox treats this as a generic downloadable file
#       filename: "{{ coreos_qcow2_img_filename }}"
#       url: "http://{{ local_ip }}:{{ http_file_server_port }}/{{ coreos_qcow2_img_filename }}"
#     body_format: json
#     validate_certs: false
#   register: qcow2_download
#   when: not core_qcow_exists or wrong_size_file
#   failed_when: qcow2_download.status != 200 and "already exists" not in (qcow2_download.content|default("")|string)

# - name: Wait for QCOW2 download to complete
#   uri:
#     url: "https://{{ proxmox_api_host }}:8006/api2/json/nodes/{{ proxmox_node_name }}/storage/{{ storage_pool }}/content"
#     method: GET
#     headers:
#       Cookie: "PVEAuthCookie={{ pve_auth_cookie }}"
#       CSRFPreventionToken: "{{ pve_csrf_token }}"
#     validate_certs: false
#   register: storage_content
#   until: >
#     storage_content.json.data | selectattr('volid', 'equalto', storage_pool + ':iso/' + coreos_qcow2_img_filename) 
#     | map(attribute='format') | select('defined') | list | length > 0
#   retries: 30
#   delay: 10
#   when: not core_qcow_exists or wrong_size_file

# Define the ignition config as a variable for easier reading
- name: Create network_config file contents
  set_fact:
    network_config: |
      [connection]
      id=Wired connection 1
      type=ethernet
      match-device=type:ethernet

      [ipv4]
      address1={{ coreos_ip }}/{{ coreos_cidr }},{{ coreos_gateway }}
      method=manual

- name: Create ignition JSON string
  set_fact:
    ignition_config: >-
      {
        "ignition": {
          "version": "3.0.0"
        },
        "passwd": {
          "users": [
            {
              "name": "{{ coreos_username }}",
              "passwordHash": "$y$j9T$icTH9ilSsldG.Sew1Ipk./$P4/ewJbHmjiKy99l7Z9bcen5dVYRf0SetM3C2l8VKn2",
              "sshAuthorizedKeys": ["{{ ssh_key['content'] | b64decode | trim }}"],
              "groups": [
                "sudo",
                "docker"
              ]
            }
          ]
        },
        "storage": {
          "files": [
            {
              "path": "/etc/NetworkManager/system-connections/static.nmconnection",
              "mode": 384,
              "contents": {
                "source": "data:text/plain;charset=utf-8;base64,{{ network_config | b64encode }}"
              }
            }
          ]
        }
      }

# Modify the ignition json to replace commas with double-commas
- name: Clean ignition JSON
  set_fact:
    ignition_config: "{{ ignition_config  | to_json | quote | regex_replace(',', ',,') }}"

- name: Debug cleaned ignition JSON
  debug:
    msg: "Cleaned ignition config: {{ ignition_config }}"

# Create the VM using the QCOW2 image in one step
#   changed from scsi0: "local:iso/{{ coreos_qcow2_img_filename }},format=qcow2"
- name: Create VM on Proxmox with imported disk
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node_name }}"
    name: "{{ coreos_vm_name }}"
    cores: "{{ coreos_cores }}"
    memory: "{{ coreos_memory }}"
    ostype: "l26"
    onboot: true
    autostart: true
    net:
      net0: "virtio,bridge=vmbr0"
    state: present
    timeout: 600
    scsi:
      scsi0: "/tmp/{{ coreos_qcow2_img_filename }},format=qcow2"
    args: "-fw_cfg name=opt/com.coreos/config,string={{ ignition_config }}"
  register: vm_create
  delegate_to: localhost
      
# Start VM
- name: Start VM on Proxmox
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node_name }}"
    vmid: "{{ vm_create.vmid }}"
    state: started
  delegate_to: localhost

- name: Wait for SSH to be available
  wait_for:
    host: "{{ coreos_ip }}"
    port: 22
    delay: 2
    timeout: 300
    state: started
  delegate_to: localhost

- name: Add VM to inventory
  add_host:
    name: "{{ coreos_ip }}"
    groups: new_vms
    ansible_user: "{{ coreos_username }}"
    ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
