---
# Homepage configuration
homepage_enabled: false  # TODO: Rewrite to use portainer_stack
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "v0.9.13"

# Directories
homepage_config_dir: "/opt/homepage"

# Network
homepage_port: 3000

# Dashboard settings
homepage_title: "Sophon Homelab"
homepage_locale: "en-US"

# Service discovery - set to true to auto-discover docker containers
homepage_docker_discovery: true
