---
- name: Pull portainer-ce container image locally
  ansible.builtin.command:
    cmd: podman pull docker.io/portainer/portainer-ce:{{ portainer_image_tag }}

- name: Save portainer image to tar file
  ansible.builtin.command:
    cmd: >-
      podman save -o {{ portainer_local_download_dir }}/portainer-ce.tar
      portainer/portainer-ce:{{ portainer_image_tag }}
    creates: "{{ portainer_local_download_dir }}/portainer-ce.tar"

- name: Pull coredns container image locally
  ansible.builtin.command:
    cmd: podman pull docker.io/coredns/coredns:{{ coredns_image_tag }}

- name: Save coredns image to tar file
  ansible.builtin.command:
    cmd: >-
      podman save -o {{ portainer_local_download_dir }}/coredns.tar
      coredns/coredns:{{ coredns_image_tag }}
    creates: "{{ portainer_local_download_dir }}/coredns.tar"
