---
- name: Pull portainer-ce container image locally
  command: podman pull docker.io/portainer/portainer-ce:{{ portainer_image_tag }}

- name: Save portainer image to tar file
  command: podman save -o {{ local_download_dir }}/portainer-ce.tar portainer/portainer-ce:{{ portainer_image_tag }}
  args:
    creates: "{{ local_download_dir }}/portainer-ce.tar"

- name: Pull coredns container image locally
  command: podman pull docker.io/coredns/coredns:{{ coredns_image_tag }}

- name: Save coredns image to tar file
  command: podman save -o {{ local_download_dir }}/coredns.tar coredns/coredns:{{ coredns_image_tag }}
  args:
    creates: "{{ local_download_dir }}/coredns.tar"
  