---
- name: Deploy CoreDNS to Portainer
  tasks:
    - name: Set deployment variables
      set_fact:
        validate_certs: false
        http_file_server_ip: "{{ ansible_default_ipv4.address }}"

    - name: Check if CoreDNS image exists
      ansible.builtin.raw: podman images | grep -q "{{ coredns_image_name }}[ ]*{{ coredns_image_tag }}"
      delegate_to: "{{ coreos_ip }}"
      register: coredns_image_exists
      failed_when: false
      changed_when: false

    - name: Download and load coreDNS image from HTTP file server
      ansible.builtin.raw: |
        cd /tmp && 
        curl -o coredns.tar http://{{ http_file_server_ip }}:{{ http_file_server_port }}/coredns.tar && 
        podman load -i coredns.tar &&
        rm -f coredns.tar
      delegate_to: "{{ coreos_ip }}"
      when: coredns_image_exists.rc != 0

    - name: Create new resolved.conf with DNSStubListener disabled
      ansible.builtin.raw: |
        echo '[Resolve]' > /etc/systemd/resolved.conf
        echo 'DNSStubListener=no' >> /etc/systemd/resolved.conf
      become: true
      delegate_to: "{{ coreos_ip }}"

    - name: Restart systemd-resolved service
      ansible.builtin.raw: systemctl restart systemd-resolved
      become: true
      delegate_to: "{{ coreos_ip }}"

    - name: Generate docker-compose content in base64
      set_fact:
        docker_compose_base64: "{{ lookup('template', 'templates/docker-compose.yml.j2') | b64encode }}"

    - name: Deploy CoreDNS stack using portainer
      include_role:
        name: portainer_deploy
      vars:
        portainer_url: "https://{{ coreos_ip }}:{{ portainer_port }}"
        stack_name: "coredns"
        docker_compose_content_decoded: "{{ docker_compose_base64 | b64decode }}"
